### ISSUE TITLE
It still got a logoct.png when downloading from cartoonmad

### ISSUE THREAD

**Issue by obxyann** [eight04/ComicCrawler#80]
It still got a logoct.png when downloading from cartoonmad every two images
Start analyzing http://www.cartoonmad.com/comic/3209.html
...
Downloading ep 第 001 話
Downloading 第 001 話 page 1: http://fun8.us/img/logoct.png
Downloading 第 001 話 page 2: http://web2.cartoonmad.com/.../002.jpg
Downloading 第 001 話 page 3: http://web2.cartoonmad.com/.../003.jpg
Downloading 第 001 話 page 4: http://fun8.us/img/logoct.png
...

**Comment by eight04** [comment]
I can't even download images from it:
```
Downloading ep 第 001 話
Traceback (most recent call last):
  File "d:\dev\comiccrawler\comiccrawler\core\__init__.py", line 581, in error_l
oop
    process()
  File "d:\dev\comiccrawler\comiccrawler\core\__init__.py", line 531, in downloa
d
    crawler.init()
  File "d:\dev\comiccrawler\comiccrawler\core\__init__.py", line 372, in init
    self.init_images(self.ep.current_page - 1)
  File "d:\dev\comiccrawler\comiccrawler\core\__init__.py", line 379, in init_im
ages
    self.get_images()
  File "d:\dev\comiccrawler\comiccrawler\core\__init__.py", line 498, in get_ima
ges
    self.ep.current_url
  File "d:\dev\comiccrawler\comiccrawler\mods\cartoonmad.py", line 25, in get_im
ages
    return re.search('img src="(http://web\.cartoonmad\.com.+?)"', html).group(1
)
AttributeError: 'NoneType' object has no attribute 'group'
```
Which version you are using? `comiccrawler --version`

**Comment by obxyann** [comment]
Sorry...i didn't use 'pip install --upgrade comiccrawler' to update to last version...
I am still in '2017.3.9' !!
After upgrade to 2017.9.9 it failed to download as same as you for any link from cartoonmad...
